# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- build_on_nix_systems

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    git submodule update --init --recursive
  displayName: 'update submodules'

- template: git submodule 

- task: CMake@1
  inputs:
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    cmakeArgs: '-S $(Build.SourcesDirectory) -Bbuild'

- task: CMake@1
  inputs:
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
    cmakeArgs: '--build $(Build.SourcesDirectory)/build'